apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-app
spec:
  selector:
    matchLabels:
      app: docker-k8s-app
  replicas: 3
  template:
    metadata:
      labels:
        app: docker-k8s-app
    spec:
      containers:
      - name: docker-k8s-app
        image: docker-k8s-app:1.0
        imagePullPolicy: IfNotPresent
        ports: 
         - containerPort: 8080
